### ISSUE TITLE
Consolidate duplicated Javascript code in single file

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#11]
Some part of the Javscript code used to provide the interactive elements of the site, are specific to particular pages.  Other parts of the Javascript code are used across multiple pages, and are currently duplicated in each HTML file.

Duplication results in difficulties:

1. harder maintenance/fixing: need to update the code on each page individually, and these can be missed/overlooked
2. browser and proxy server are not able to cache data, and must re-download each time.
3. pages and results take longer to download, resulting in a slower experience for the user.
4. debugging is significantly harder as different code can be used in different situations

Ideally all of the common code should be moved to a single `.js` file, and this file called using `<script …>` in the individual HTML files.  A bonus is the likelyhood of speed-ups because the browser can pre-cache both the Javascript and the pre-compiled Javacript across page loads or changes.

**Comment by georgbuechner** [comment]
It's in prograss. Code as started being migrated to web/user.js

**Comment by georgbuechner** [comment]
We split all the javascrip, css and html code. The next step would be to search these file for dublicate code in javescript or css file. I could not find any dublicated javascript code. I guess the dublicate css code is somehow hidden, as there are no dublicated css classes. I would be neccessariy to compare all classes and see, which classes could be merged into one. This, however, seems to be very much effort, for a more or less small effect. Due to this fact, we decided to postpone this for now.
