### ISSUE TITLE
Bei mehreren Suchbegriffen keine Treffer im einzelnen Buch

### ISSUE THREAD

**Issue by rolandborgards** [ShadowItaly/clas-digital#131]
Die Suche nach "Polypen des Meeres" bringt mir folgende Treffer (sehr gut!):
https://www.clas-digital.uni-frankfurt.de/search?q=polypen+des+meeres

Dann gehe ich auf "Willbrand 1833" und komme hierher:
https://www.clas-digital.uni-frankfurt.de/search?q=polypen+des+meeres

Und da sind dann keine Treffer mehr angegeben. Das ist wahrscheinlich ein Problem, dass nur bei mehren Suchwörtern auftaucht, hat also keine hohe Priorität!

**Comment by ekoehring** [comment]
I can reproduce this error and found the reason!

1) Searching for "polypen" works fine (https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=polypen&scanId=AKZ5SHJB&fuzzyness=0#page15)

2) Searching for "polypen meeres" gives results, but no highlighting (https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=polypen%20meeres&scanId=AKZ5SHJB&fuzzyness=0#page33)

3) Searching for "polypen des meeres" gives no results in GetBooks (https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=polypen%20des%20meeres&scanId=AKZ5SHJB&fuzzyness=0)

If I edit the urls to have + instead of %20 (or space), it works!!

Roland, here is a link for you: https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=polypen+des+meeres&scanId=AKZ5SHJB&fuzzyness=0#page265

So, reproduced and diagnosed, someone else needs to fix it :)
