### ISSUE TITLE
Ensure Google can index Book content, not "Could not load metadata sorry for that :( Could not load hit list sorry for that."

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#152]
Search for "clas digital":

* https://www.google.com/search?q=clas+digital

One of the first results returned is:

1. https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=grasm%C3%BCcke&scanId=QH9C92KT&fuzzyness=0

Which shows up in the (Google) search result at:

```
[icon] clas-digital.www.uni-frankfurt.de › GetBooks

clas digital
https://www.clas-digital.uni-frankfurt.de/
Could not load metadata sorry for that :( Could not load hit list sorry for that.
```
The actual title of the book is: "Schubert (1830). Lehrbuch der Naturgeschichte für Schulen und zum Selbstunterrich"

Problems here:

1. Title indexed by Google should be "Schubert (1830). Lehrbuch der …" not "clas digital"
2. Content indexed by Google should be "Singvögel: Arten von Grasmücken, (Sylvia) die ſich alle durch einen dünnen …" not "Could not load metadata sorry for that :( Could not load hit list sorry for that."
3. URL should be `/books/QH9C92KT?highlight=grasm%C3%BCcke` not `/GetBooks.html?query=grasm%C3%BCcke&scanId=QH9C92KT&fuzzyness=0`

**Comment by alleonhardt** [comment]
I could confirm the issue, this is indeed a very important issue so we are going to tag this high priority

**Comment by alleonhardt** [comment]
Should be fixed by https://github.com/ShadowItaly/clas-digital/commit/ea5db6748c59879ea0d8b7bcef9505169e427dc8 and https://github.com/ShadowItaly/clas-digital/commit/c09cf941701b7cb77d39fb6728e0149a09b7f965

URL Layout changed as well the sites are now available at: https://www.clas-digital.uni-frankfurt.de:9991/books/PZES2R5E/view?highlight=hund aka GetBooks.html
and https://www.clas-digital.uni-frankfurt.de:9991/books/PZES2R5E/meta aka ShowMetadata.html

Old URLS will still work though: https://www.clas-digital.uni-frankfurt.de:9991/GetBooks.html?scanId=PZES2R5E&highlight=hund


If I missed something feel free to reopen :)
