### ISSUE TITLE
Website not syncing to Zotero

### ISSUE THREAD

**Issue by PaulMueller9x** [ShadowItaly/clas-digital#225]
I noticed that the changes I made during the last 4 days in Zotero are not showing up on the website, even after several restarts. For example "Marvin, G." still shows up in the author list, even though he should now be "Marvin, Garry".

Sorry if this a known issue. Have a nice day!

**Comment by sladen** [comment]
* https://www.clas-digital.uni-frankfurt.de/catalogue/authors/garry-marvin/ (6 books)
* https://www.clas-digital.uni-frankfurt.de/catalogue/authors/g.-marvin/ (1 book)

**Comment by ekoehring** [comment]
The book showing as g.-marvin on the website is XCFFDRQC.
In Zotero it is showing as Garry Marvin, modified 4 days ago:
![image](https://user-images.githubusercontent.com/40890481/81829340-166be400-953b-11ea-82ee-24d2263b41c5.png)
This makes the consolidating of zotero data quite hard.

**Comment by alleonhardt** [comment]
Ok. We are on the problem, thanks for the feedback.

**Comment by alleonhardt** [comment]
This is fixed by https://github.com/ShadowItaly/clas-digital/commit/971044274ca85dda25c2f362c4da45462d589ed6. The old links are still valid, but when one looks in the catalogue and does a search for "marvin" only one author shows up with 7 books. 

If you find more examples of synchronisation problems please tell us.
