### ISSUE TITLE
Still some syncing issues

### ISSUE THREAD

**Issue by PaulMueller9x** [ShadowItaly/clas-digital#227]
Some syncing issues were fixed, but there are still some who are not.
Here are some examples of things that should be changed:

Oken: https://www.clas-digital.uni-frankfurt.de/catalogue/authors/-oken/

Oken, Lorenz: https://www.clas-digital.uni-frankfurt.de/catalogue/authors/lorenz-oken/

Reichenbach, H. G. L. : https://www.clas-digital.uni-frankfurt.de/catalogue/authors/h.g.l.-reichenbach/

Reichenbach, Heinrich Gottlieb Ludwig: https://www.clas-digital.uni-frankfurt.de/catalogue/authors/heinrich-gottlieb-ludwig-reichenbach/

Zithlsperger, Helga (spelling mistake): https://www.clas-digital.uni-frankfurt.de/catalogue/authors/helga-zithlsperger/

Zitzlsperger, Helga: https://www.clas-digital.uni-frankfurt.de/catalogue/authors/helga-zitzlsperger/

Wells, H. G. was deleted because his books "The Island of Dr. Moreau" is primary literature, but he still shows up: https://www.clas-digital.uni-frankfurt.de/catalogue/authors/h.g.-wells/

![zotero2](https://user-images.githubusercontent.com/65245329/81939827-221ce080-95f7-11ea-9c34-fd1c92df9a8c.png)

This is the Zithlsperger spelling mistake fixed in Zotero.

**Comment by ekoehring** [comment]
The problem seems to be solved - was there a fix?

**Comment by georgbuechner** [comment]
There was no fix. Is it possible, that you didn't wait till the next day to check? Zotero is updated every day at around midnight, so any changes done before midnight will not directly be reflected on the website.

**Comment by ekoehring** [comment]
Yes, of course - when I checked the changes Paul M mentioned, they were already 4 days old. Zotero shows the timestamp of data modification (see screenshot above and compare to the time of the issue).

**Comment by alleonhardt** [comment]
It is possible that the problem itself does not exist/ is a different issue. The catalogue does not remove deprecated data at the moment, this means when changing the name Oken to Lorenz, Oken the link https://www.clas-digital.uni-frankfurt.de/catalogue/authors/-oken/ is still valid and one can click it and see the old results, but one cannot find this link anywhere on the main site by searching the catalogue. See issue https://github.com/ShadowItaly/clas-digital/issues/234. So we have the suspicion that the program synchronizes the data without problems, but the links which vanish due to the updated metadata still exist and lead to the impression of wrong synchronization.

We would suggest to change the metadata of one book/author/collection, then on the next day try to find the same book/author/collection by navigating through the catalogue without storing a link to the old metadata. If the book/author/collection has changed we can assume that the synchronization works. If not please comment here again and we will start a throughout search of the program.

**Comment by ekoehring** [comment]
I understand that. But when this issue was opened, the links _could_ be found on the catalogue pages. It has not happened before and not since (I did tests like the ones you describe every two or three days). I will let you know if I observe it again, but let's hope it was a one time weirdness.

**Comment by alleonhardt** [comment]
Ok perfect I will close this issue then, feel free to reopen when encountering the syncing issues again!
