### ISSUE TITLE
All creators are regarded as authors

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#254]
As one can see in the book: https://www.clas-digital.uni-frankfurt.de:9991/books/GQ7H6ZPG. There are only 2 authors and the other 2 are editors. The program treats all 4 of them as authors. There needs to be advanced parsing of the creatorType.

**Comment by georgbuechner** [comment]
This has been fixed with the latest commit. In the list of authors on the metadatapage, each list element show creator type in brackets behind the author name. People listed as authors, which are never occur with the creatorsType tag "author", are not listed as authors in the catalogue. 
If you would which, to show editors or publishers in the catalogue as authors, please let me know.

**Comment by ekoehring** [comment]
There is a difference: Some entries are books, edited by editors (itemtype: book ). Example:
https://www.clas-digital.uni-frankfurt.de:9991/books/AFN3A8TB/
These editors need to be shown as authors, so that the catalogue entry for the author includes this book:
https://www.clas-digital.uni-frankfurt.de:9991/catalogue/authors/linda-kalof/

On the other hand, there are book sections (and some journal articles). They have authors and editors, in this case only the authors need to be interpreted as authors (booksection and journal article).


Example for a booksection: https://www.clas-digital.uni-frankfurt.de:9991/books/ZHI9S5GX/

Is it possible to make that distinction? Otherwise the author-catalogue would either lack a lot of titles, or be overcrowded. Think about RB himself: He has edited the "Handbuch Tiere" which needs to be found under his author catalogue entry. But not all the articles in this book, written by other people!

**Comment by sladen** [comment]
```
for book in books:
  if (book.ItemType == book):
    catalogue.authors.add(book.authors + book.editors);

  if (book.ItemType == bookSection):
    catalogue.authors.add(book.authors);
```

**Comment by georgbuechner** [comment]
This seems very logical to me. I will work on this soon.

**Comment by georgbuechner** [comment]
This is currently implemented as: 
`if itemType == bookSection:
    catalogue.authors.add(book.authors)
else:
    catalogue.authors.add(book.authors + book.editors)`

Which means, that the default is to add `editors and authors` to the catalogue and only for books with the itemType "bookSection" just authors are added to catalogue.
