### ISSUE TITLE
Style: Uni frankfurt like top navigation bar

### ISSUE THREAD

**Issue by ShadowItaly** [ShadowItaly/clas-digital#42]
Make the site look a bit more similar to the uni frankfurt site, 
style wise. So maybe change the color of the top navbar to a bit more fitting blue.

Compare to:
- http://www.goethe-university-frankfurt.de/en?locale=en

**Comment by ekoehring** [comment]
Color information: http://www.muk.uni-frankfurt.de/52945514/Farben

**Comment by ShadowItaly** [comment]
Perfekt danke.

**Comment by georgbuechner** [comment]
Color in top bar changed. What do you think of the changes?

**Comment by ekoehring** [comment]
Fine with me, not very exciting but I guess that is the university color scheme...
I am wondering whether it makes sense to change the blue of the search results to the same blue? I think "es beißt sich", but am open to suggestions.

**Comment by georgbuechner** [comment]
I understand what you are seeing, but in my opinion, we should not change the color of what people know to be the color of a link. Since we added the clas digital logo there is enough blue in the darker color to make it look less strange. The only other option I see would be to abandon the blue and use the orange layout instead. That would however abandon the Goethe-Uni style. Which I believe to be kinda important.

**Comment by sladen** [comment]
It will be easier to experiment/test/review options after the CSS has been consolidated (see bug #10); at the moment, things are too spread out to easily make this kind of style change reliably.

(The ideal would be to *override* the *minimum* of behaviour/styling as possible; so that links/widgets work as expected on various OS/Browser/Device combinations—though certainly agree that the different, constrasting blues are annoying; what is the main Uni-Frankfurt website doing?).

**Comment by georgbuechner** [comment]
Looking at the main Uni-Frankfurt page, they are using kinda 3 sorts of blue :D http://www.goethe-university-frankfurt.de/en?locale=en

**Comment by georgbuechner** [comment]
these are the link colors used by the goethe university:
1. `#005eaa`
2. `rgb(0, 94, 170)`
(Both retrieved from link posted above)

**Comment by sladen** [comment]
Geothe house colours added in 1d61844 and CLAS logo re-coloured to Goethe house colours in bug #67 and bug #75.
