### ISSUE TITLE
Should auto restart after crash

### ISSUE THREAD

**Issue by sladen** [ShadowItaly/clas-digital#52]
After the server process has crashed, the service remains stopped:

  http://clas-digital.uni-frankfurt.de/

The solution needs the following:

1. Document *precisely* how to restart the server process.
2. Turn this documentation into a `service` wrapper or script
3. Deploy the service wrapper so that a watchdog function is taken care of

Note that this may require restarting the server process inside `screen` for debugging/logging.

**Comment by georgbuechner** [comment]
After a serverrestart the services started by this file
https://github.com/ShadowItaly/clas-digital/blob/cpp/src/clas-digital.service
which gets installed in /etc/systemd/system/clas-digital.service
This is done by running sudo make install. 

In order to debug:
1. shutdown server by using `sudo systemctl stop clas-digital`
2. compile changes with `make` in build
3. Run `sudo make install` in build 
Now the server will be running. To see debug output, call `sudo journalctl -f -u clas-digital`
