### ISSUE TITLE
Does not find all results which are in the book

### ISSUE THREAD

**Issue by alleonhardt** [ShadowItaly/clas-digital#88]
This will not find 'fuchs' on page 242 but fuchs is on page 242.
https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=fuchs&scanId=36XFP384&fuzzyness=0#page242

**Comment by alleonhardt** [comment]
https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=hund&scanId=PZES2R5E&fuzzyness=1#page13

Findet 'ihrerhundert' auf Seite 13 aber dieses Wort gibt es nicht es gibt nur 'ihrer hundert'

**Comment by alleonhardt** [comment]
https://www.clas-digital.uni-frankfurt.de/GetBooks.html?query=hund&scanId=PZES2R5E&fuzzyness=1#page265

Alle Worte 'hundinn' gibt es nicht auf den Seiten aber werden als Treffer angezeigt.

**Comment by georgbuechner** [comment]
> This will not find 'fuchs' on page 242 but fuchs is on page 242.
> Findet 'ihrerhundert' auf Seite 13 aber dieses Wort gibt es nicht es gibt nur 'ihrer hundert'

Problem here is, that for some reason some words are spellt together, while some others are not
I'm working on this. The error is probably in extractWordsFromString from src/books/func.cpp'


>Alle Worte 'hundinn' gibt es nicht auf den Seiten aber werden als Treffer angezeigt.

Here the problem is, that my search ignores ü, ä, è etc. to find better matches. The word on the Page is Hündinn" which then won't be found.
